[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "caelestia"
requires-python = ">=3.13"
dynamic = ["version"]

[project.scripts]
caelestia = "caelestia:main"

[tool.hatch.version]
source = "vcs"
